name: CleanPulse
version: 2.0.0
main: com.tuservidor.cleanpulse.CleanPulse
api-version: '1.21'
author: Dafealru
description: The Ultimate Next-Gen Non-Destructive Server Optimizer & Anti-Lag Suite
commands:
  cleanpulse:
    description: Main CleanPulse administrative & performance command
    aliases: [cp, pulse]
  trash:
    description: Open disposable trash bin GUI
    aliases: [basura, bin]
permissions:
  cleanpulse.admin:
    description: Full administration access for CleanPulse
    default: op
  cleanpulse.use:
    description: Access to player-level commands like /cp filter, /cp death, /cp myfarm
    default: true
  cleanpulse.trash:
    description: Access to /trash command
    default: true
